server:
  port: 9000
spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: baidu
          uri: https://baidu.com
          predicates:
            - Path=/baidu/**
          filters:
            - StripPrefix=1
    nacos:
      username: nacos
      password: nacos
      server-addr: localhost:8848
      discovery:
        enabled: true